server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.com.pv.rest_api_app=DEBUG
logging.file.name=logs/rest-api-app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %p - %m%n